### ISSUE TITLE
Issue with the `runReport` function.

### ISSUE THREAD

**Issue by Shashankti** [BIMSBbioinfo/RCAS#15]
Thank you for providing this tool, however I have come across a small issue.
The following part of code from the `runReport` function causes error due to changed structure of the `BSGenome` package.
```
  db <- checkSeqDb(genomeVersion)
  # get species name 
  # this is needed for gprofiler functional enrichment 
  fields <- unlist(strsplit(db@organism, ' '))
```
which gives the error

```
Loading required package: rtracklayer
Error in strsplit(db@organism, " ") : 
  no slot of name "organism" for this object of class "BSgenome"
```
This can be fixed by updating the line to
```
  db <- checkSeqDb(genomeVersion)
  # get species name 
  # this is needed for gprofiler functional enrichment 
  fields <- unlist(strsplit(db@metadata$organism, ' '))
```

I am not familiar with pull request policy, therefore I am raising it as an issue here.

**Comment by borauyar** [comment]
@Shashankti Thank you very much for the feedback and for the bug fix. It should be fixed in the latest bioc release 1.28.2 and development versions 1.29.2.
