### ISSUE TITLE
Error in previously working function getFeatureBoundaryCoverage

### ISSUE THREAD

**Issue by Braulium** [BIMSBbioinfo/RCAS#16]
Dear RCAS team,

First, thanks for creating the RCAS package, I use it frequently to interrogate my CLIP datasets, and it's extremely useful.

Recently, when I try to run the function getFeatureBoundaryCoverage, I get the following error:
  invalid class "ScoreMatrix" object: superclass "mMatrix" not defined in the environment of the object's class

In a previously working code chunk. I could not find out what was happening, and it did not seem to depend on my datasets.
Any idea of what could be happening?

Many thanks.

Best regards,
Raul

**Comment by borauyar** [comment]
Hi @Braulium,
Thank you for using it :) 

Can you maybe provide an example code and its output to demonstrate the error?

Did you try working on a fresh session? Maybe just create a new session with no packages loaded. Just load RCAS and see if it works.

**Comment by Braulium** [comment]
Hi Borauyar,

Many thanks for your answer! Just today I found the solution online. Installing a previous version of the Matrix package solved the issue.

**Comment by borauyar** [comment]
Great! Thanks for letting me know.
