### ISSUE TITLE
seqLogo Error

### ISSUE THREAD

**Issue by YPerevalova** [BIMSBbioinfo/RCAS#17]
Good day RCAS Team!

Firstly, thanks for the fabulous package of tools! It's been a lifesaver!
I was wondering if it would be possible to resolve an issue I'm having with the motif discovery module. I've been using custom data and walking through it step-by-step in your online vignette. Everything works fine and generates all the expected data/figures until I get to generating the seqLogo, where I ger the following error:

```
> seqLogo::seqLogo(getPWM(motifResults$matches_query[[1]]))

Error in getPWM(motifResults$matches_query[[1]]) : 

  could not find function "getPWM"
```

I've tried to reinstall seqLogo from both Bioconductor and the Github, and it seems to work fine, and I've also reinstalled RCAS from both Bioconductor and directly from the Github. I'm a little uncertain if this is an RCAS error or one specific to seqLogo. Could you please advise on this issue?

Thanks!

**Comment by borauyar** [comment]
Hi @YPerevalova, 
Thank you! Great to hear you find the package useful for your work. 

I looked into this issue, but I can't reproduce the error. 

The error is not about the seqLogo package. It is about the `getPWM` function from RCAS. This function basically extracts a position weight matrix (PWM) from a given collection of sequences. 

Can you maybe try this: 
`RCAS::getPWM(motifResults$matches_query[[1]])`  and see if it returns a score matrix with 4 rows and 6 columns? 

The function is exported by RCAS, so if you have already loaded RCAS with `library(RCAS)`, the function should be accessible. 

If it still doesn't work, can you make sure you are using the latest RCAS package from Bioconductor?
Hope this helps,
Bora

**Comment by YPerevalova** [comment]
Good day, @borauyar!

Thanks so much for the help! I checked the version (it was downloading 1.20.4) and discovered that my Bioconducter was just glitching out and not delivering me the newest updates on packages. Nuked the whole thing, redownloaded to a clean slate and everything works fantastically now. Thanks again, Bora, and so sorry for the naive question - very green when it comes to computation.

Have a lovely day!
Yelena

**Comment by borauyar** [comment]
Great that it worked out. Thanks for letting me know! 
Bora
