### ISSUE TITLE
Increased variety of genomic annotations and genome versions

### ISSUE THREAD

**Issue by al2na** [BIMSBbioinfo/RCAS#8]
We plan to keep adding more and more useful plots and tables that can enrich the biological context of the given input datasets. For instance, plots that show the distribution of mutations and polymorphisms in relation to the input transcript segments could provide useful insights in prioritizing potential targets for follow-up studies. Moreover, we would like to provide support for an expanded collection of species (e.g. other eukaryotic model organisms such as Zebrafish) and additional genome builds for the currently supported species (e.g. hg38 for human, mm10 for mouse).

**Comment by borauyar** [comment]
RCAS now supports all genome versions available in `BSgenome::available.genomes`.
